disable-other-villagers: true
block-villager-spawns: false
enable-spawn-verifier: false
enable-purchase-logging: false
save-instantly: true

enable-world-guard-restrictions: false
enable-towny-restrictions: false

create-player-shop-with-command: false
simulate-right-click-on-command: true
require-chest-recently-placed: true
protect-chests: true
max-shops-per-player: 0
max-chest-distance: 15

shop-creation-item: 383
shop-creation-item-data: 120
shop-creation-item-name: ""
deleting-player-shop-returns-egg: false

enable-villager-shops: true

enable-sign-shops: true
sign-shop-first-line: "[SHOP]"

editor-title: "Shopkeeper Editor"
save-item: 133
delete-item: 51

currency-item: 388
currency-item-data: 0
zero-item: 341

high-currency-item: 133
high-currency-item-data: 0
high-currency-value: 9
high-currency-min-cost: 20
high-zero-item: 341

language: en

msg-button-save: "&aSave"
msg-button-type: "&eChoose Appearance"
msg-button-delete: "&4Delete"

msg-selected-normal-shop: "&aNormal shopkeeper selected (sells items to players)."
msg-selected-book-shop: "&aBook shopkeeper selected (sell books)."
msg-selected-buy-shop: "&aBuying shopkeeper selected (buys items from players)."
msg-selected-trade-shop: "&aTrading shopkeeper selected (trades items with players)."
msg-selected-chest: "&aChest selected! Right click a block to place your shopkeeper."
msg-must-select-chest: "&aYou must right-click a chest before placing your shopkeeper."
msg-chest-too-far: "&aThe shopkeeper's chest is too far away!"
msg-chest-not-placed: "&aYou must select a chest you have recently placed."
msg-shop-create-fail: "&aYou cannot create a shopkeeper there."
msg-too-many-shops: "&aYou have too many shops."

msg-player-shop-created: |
    &aShopkeeper created!
    &aAdd items you want to sell to your chest, then
    &aright-click the shop while sneaking to modify costs.
msg-book-shop-created: |
    &aShopkeeper created!
    &aAdd written books and blank books to your chest, then
    &aright-click the shop while sneaking to modify costs.
msg-buy-shop-created: |
    &aShopkeeper created!
    &aAdd one of each item you want to sell to your chest, then
    &aright-click the shop while sneaking to modify costs.
msg-trade-shop-created: |
    &aShopkeeper created!
    &aAdd items you want to sell to your chest, then
    &aright-click the shop while sneaking to modify costs.
msg-admin-shop-created: |
    &aShopkeeper created!
    &aRight-click the shop while sneaking to modify trades.

debug: false